name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: dependencies
        run: sudo apt-get install make gfortran libopenmpi-dev doxygen

      - name: doxygen
        run: cd $GITHUB_WORKSPACE/src && doxygen

      - name: build Ses3d-NT
        run: cd $GITHUB_WORKSPACE/src && make

      - name: build tests and execute
        run: |
          cd $GITHUB_WORKSPACE/src/examples && make
          for test in $GITHUB_WORKSPACE/src/examples/*test; do $test; done
